### PR TITLE
Add msf host provisioning

### PR DESCRIPTION
**Pull request by jmartin-r7**
Adds a template to build the Metasploit-Framework host system on ubuntu 16.04.

This build extends on a base boxcutter/ubuntu build and will deploy into ESXI.

Note: when build is in progress the user must have permissions to write to `<INSTALL_PATH>/tmp & <INSTALL_PATH>/boxcutter/ubunutu/packer_cache`

### CODE REVIEW

**Comment by bwatters-r7** [comment]
How do you go about launching it?  What would the things to check to verify success?

**Comment by jmartin-r7** [comment]
This creates a new host with hostname `msf_host`.  The same options are available as in `build_baselines.py`.

```
$ python build_msf_host.py -h
build_msf_host.py [options]
-c <file>, --esxiConfig=<file>   use alternate hypervisor config file
-p <string>, --prependString=<file>   prepend string to the beginning of VM names
-r, --replace                     replace existing msf_host
```

ESXI catalog name matching is case sensitive, new targets will have standard `vagrant` user with metasploit-framwork git repo in `~/rapid7/metasploit-framework` and `pyenv` with 2.7.13 installed.

**Comment by jmartin-r7** [comment]
The cleanup script in https://github.com/boxcutter/ubuntu fills the thin provisioned disk for local export.  This can be addressed manually by removing the `baseline` snapshot and using `vmkfstools -K disk.vmdk` to thin the disk.  Might be worth looking into adjusting to actually thin provision this build.

**Comment by bwatters-r7** [comment]
Run straight from the pr:
```
builder@ubuntu:~/rapid7/metasploit-baseline-builder$ python build_msf_host.py -p TEST_ -c '/home/builder/rapid7/metasploit-baseline-builder/main_config.json'
  0%|                                                                                                                                  | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "build_msf_host.py", line 106, in <module>
    main(sys.argv)
  File "build_msf_host.py", line 101, in main
    build_base(target, replace_existing=replace_vms, vmServer=vm_server, prependString=prependString)
  File "build_msf_host.py", line 36, in build_base
    packer_obj = packerMod(packerfile)
  File "/home/builder/rapid7/metasploit-baseline-builder/lib/packerMod.py", line 8, in __init__
    with open(packer_file) as packer_source:
IOError: [Errno 2] No such file or directory: 'ubuntu.json'
```

**Comment by jmartin-r7** [comment]
This adds a repo as a submodule, per `README.md` updates:
```
git submodules init
git sudmodules update
```

**Comment by jmartin-r7** [comment]
Added your fix to `gnome-terminal`, as a future iteration I would like to trim down this install to a server env without X11 installed but this will due for now.

**Comment by bwatters-r7** [comment]
Rock on; this is passing everything I think it needs to do; did you have anything to add, or can I go ahead and land it?

**Comment by bwatters-r7** [comment]
# Release notes
This adds the ability to autobuild the msf_host VMs used by payload testing.

**Pull request merged**
